# Generated by Django 5.0.2 on 2024-03-13 09:08

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13, validators=[account.models.phone_validator]),
        ),
    ]
